### ISSUE TITLE
[회원가입] 이메일

### ISSUE THREAD

**Issue by nohgijin** [woowa-techcamp-2020/market-5#8]
* 필수 입력사항

* FE
 - [x] 이메일 선택
 - [x] 이메일 직접입력인 경우 유효성 검사
 - [x] 이메일 직접입력 바로 커서 진행되도록
* BE
- [x] 이메일 파싱해서 저장

**Comment by parkjihwanjay** [comment]
프론트에서 이메일을 파싱해서 저장 후 DB에 저장하는 식으로 진행했습니다.
